services:
  - type: web
    name: rinex-api
    runtime: static
    repo: https://github.com/mehmetdopamine39-hub/sorguapileri
    plan: free
    region: frankfurt
    staticPublishPath: .
    buildCommand: echo "Static site build completed"
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
