services:
  - type: web
    name: rinex-api
    runtime: python
    repo: https://github.com/sizin-repo/adınız
    plan: free
    region: frankfurt
    buildCommand: |
      python3.11 -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python3.11 bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PATH
        value: /usr/local/bin:/usr/bin:/bin:/opt/python3.11/bin
